### ISSUE TITLE
Presence detection for several devices: wrong source_type attribute in Home Assistant

### ISSUE THREAD

**Issue by bcutter** [1technophile/OpenMQTTGateway#1755]
**Describe the bug**
In Home Assistant (HA Core 2023.3.6) the `device_tracker.xiaomi_smart_band_7` entity's attribute has `source_type: gps` even it should be `source_type: bluetooth_le`.

Interestingly, in MQTT it is correct in the device_tracker topic:
```
...
  "name": "MB/SW-tracker",
...
  "val_tpl": "{% if value_json.get('rssi') -%}home{%- else -%}not_home{%- endif %}",
  "source_type ": "bluetooth_le",
  "device": {
...
...
```

**To Reproduce**
1. Set up a Xiaomi Smart Band 7
2. Activate `BT: Publish HASS presence` switch in HA
3. Wait to auto-discover the device
4. Check device_tracker entity's attribute

**Expected behavior**
Attribute `source_type` should be `bluetooth_le` in HA, like it is in MQTT.

**Screenshots**
![grafik](https://github.com/1technophile/OpenMQTTGateway/assets/13799156/92e0671e-4be0-417f-8b71-05227df2a9e1)
![grafik](https://github.com/1technophile/OpenMQTTGateway/assets/13799156/f08ae0af-e137-4878-85ff-4d61b7a8f01f)

**Environment (please complete the following information):**
* OpenMQTTGateway version used: v1.6.0 / development `a046c8`

**Additional context**
As it is fine in MQTT but not in HA I fear you might close this issue and redirect me to... well, where?

**Comment by bcutter** [comment]
Not fixed. Will try to update HA to a newer version.

Anyway, wondering why there's not a single response after 3 months...

**Comment by DigiH** [comment]
> Interestingly, in MQTT it is correct in the device_tracker topic:

Not quite ;P took some time to really look closely, but there is a trailing space in "source_type ", messing the correct recognition up :(

Fixed with
https://github.com/1technophile/OpenMQTTGateway/pull/1853

**Comment by bcutter** [comment]
Oh great, so sometimes it's the little things right... 😄 
Can you estimate when this fix will be shipped (in a stable release)?

**Comment by DigiH** [comment]
As there are still some other issues which need addressing for the next release, a bit hard to say at the moment, but shouldn't bee too long.

**Comment by bcutter** [comment]
Alright so definitely 2024 and probably until February (or even January)? :-)

**Comment by bcutter** [comment]
Any update on this please? If I did not miss a release I tend to say we're still missing one, don't we? :-)

Please note I meanwhile discovered this for other devices provided by OMG/TheengsGateway too (other smart bands or a BM2 etc.) and therefore edited the title of this issue.
